#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  set +e
  \. "$NVM_DIR/nvm.sh"
  set -e
fi
if [ -s "$HOME/.fnm/fnm" ]; then
  set +e
  eval "$("$HOME/.fnm/fnm" env)"
  set -e
fi

npx --no -- commitlint --edit ${1}
